const notM2mFriendly = [
  {
    objectId: "1",
    itemId: "22",
    rangeEnumeration:
      "The possible values are those listed in the LwM2M Core Specification",
    unit: "",
  },
  {
    objectId: "10245",
    itemId: "0",
    rangeEnumeration: "AVAILABLE; UNAVAILABLE",
    unit: "",
  },
  {
    objectId: "10245",
    itemId: "1",
    rangeEnumeration: "UNSYNCHRONISED; SYNCHRONISED",
    unit: "",
  },
  { objectId: "10245", itemId: "8", rangeEnumeration: "0..2^28-1", unit: "" },
  { objectId: "10246", itemId: "0", rangeEnumeration: "0..2^32-1", unit: "" },
  { objectId: "10247", itemId: "1", rangeEnumeration: "0..2^32-1", unit: "" },
  { objectId: "10249", itemId: "1", rangeEnumeration: "0..2^32-1", unit: "" },
  { objectId: "10249", itemId: "6", rangeEnumeration: "0..2^32-1", unit: "B" },
  { objectId: "10249", itemId: "7", rangeEnumeration: "0..2^32-1", unit: "B" },
  {
    objectId: "10254",
    itemId: "0",
    rangeEnumeration: "0; 3.8..20.5",
    unit: "mA",
  },
  { objectId: "10308", itemId: "7", rangeEnumeration: "<7 to >12.5", unit: "" },
  { objectId: "10334", itemId: "7", rangeEnumeration: "0..2^63-1", unit: "" },
  { objectId: "10335", itemId: "4", rangeEnumeration: "0..2^63-1", unit: "" },
  {
    objectId: "10354",
    itemId: "5",
    rangeEnumeration: "0..255 bytes",
    unit: "",
  },
  { objectId: "14", itemId: "0", rangeEnumeration: "0..255 bytes", unit: "" },
  { objectId: "14", itemId: "2", rangeEnumeration: "0..255 bytes", unit: "" },
  { objectId: "19", itemId: "1", rangeEnumeration: "1 bytes", unit: "" },
  { objectId: "19", itemId: "3", rangeEnumeration: "32 bytes", unit: "" },
  { objectId: "19", itemId: "4", rangeEnumeration: "32 bytes", unit: "" },
  { objectId: "19", itemId: "5", rangeEnumeration: "2 bytes", unit: "" },
  { objectId: "20", itemId: "4013", rangeEnumeration: "8-Bits", unit: "" },
  {
    objectId: "2053",
    itemId: "6",
    rangeEnumeration: "2 Instances",
    unit: "ms",
  },
  {
    objectId: "2053",
    itemId: "7",
    rangeEnumeration: "2 Instances",
    unit: "ms",
  },
  {
    objectId: "2053",
    itemId: "8",
    rangeEnumeration: "2 Instances",
    unit: "ms",
  },
  {
    objectId: "2053",
    itemId: "9",
    rangeEnumeration: "2 Instances",
    unit: "ms",
  },
  {
    objectId: "3387",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3387",
    itemId: "800",
    rangeEnumeration:
      "0: disabled      1: normal      2: remote      3: local      255: non_responsive",
    unit: "",
  },
  {
    objectId: "3387",
    itemId: "801",
    rangeEnumeration: "1: normal      2: remote      3: local",
    unit: "",
  },
  {
    objectId: "3388",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3388",
    itemId: "500",
    rangeEnumeration: "0..64 bytes",
    unit: "",
  },
  {
    objectId: "3388",
    itemId: "501",
    rangeEnumeration: "0..64 bytes",
    unit: "",
  },
  {
    objectId: "3388",
    itemId: "912",
    rangeEnumeration: "0..64 bytes",
    unit: "",
  },
  {
    objectId: "3388",
    itemId: "908",
    rangeEnumeration: "1..64 bytes",
    unit: "",
  },
  {
    objectId: "3389",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3390",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3391",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3392",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3393",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3394",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3395",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3395",
    itemId: "202",
    rangeEnumeration:
      "0: RELEASE      1: CLICK      2: HOLD      3: DOUBLE-CLICK      255: STUCK",
    unit: "",
  },
  {
    objectId: "3396",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3396",
    itemId: "908",
    rangeEnumeration: "1..64 Bytes",
    unit: "B",
  },
  {
    objectId: "3396",
    itemId: "912",
    rangeEnumeration: "0..64 bytes",
    unit: "",
  },
  {
    objectId: "3396",
    itemId: "110",
    rangeEnumeration: "0: CONFIGURED_ON      1: FULL_ON      2: RECALL",
    unit: "",
  },
  {
    objectId: "3397",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3397",
    itemId: "908",
    rangeEnumeration: "1..64 bytes",
    unit: "",
  },
  {
    objectId: "3397",
    itemId: "912",
    rangeEnumeration: "0..64 bytes",
    unit: "",
  },
  {
    objectId: "3397",
    itemId: "110",
    rangeEnumeration: "0: CONFIGURED_ON      1: FULL_ON      2: RECALL",
    unit: "",
  },
  {
    objectId: "3398",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3398",
    itemId: "908",
    rangeEnumeration: "1..64 bytes",
    unit: "",
  },
  {
    objectId: "3399",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3399",
    itemId: "908",
    rangeEnumeration: "1..64 bytes",
    unit: "",
  },
  {
    objectId: "3399",
    itemId: "912",
    rangeEnumeration: "0..64 bytes",
    unit: "",
  },
  {
    objectId: "3399",
    itemId: "110",
    rangeEnumeration: "0: CONFIGURED_ON      1: FULL_ON      2: RECALL",
    unit: "",
  },
  {
    objectId: "3400",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3400",
    itemId: "908",
    rangeEnumeration: "1..64 bytes",
    unit: "",
  },
  {
    objectId: "3401",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3401",
    itemId: "201",
    rangeEnumeration: "0: RELEASED      1: PRESSED      2: FAULT",
    unit: "",
  },
  {
    objectId: "3401",
    itemId: "908",
    rangeEnumeration: "1..64 bytes",
    unit: "",
  },
  {
    objectId: "3402",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3403",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3404",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3405",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  {
    objectId: "3406",
    itemId: "901",
    rangeEnumeration: "0..256 bytes",
    unit: "",
  },
  { objectId: "3418", itemId: "22", rangeEnumeration: "ON;OFF", unit: "V" },
  { objectId: "9", itemId: "0", rangeEnumeration: "0..255 bytes", unit: "" },
  { objectId: "9", itemId: "1", rangeEnumeration: "0..255 bytes", unit: "" },
  { objectId: "9", itemId: "3", rangeEnumeration: "0..255 bytes", unit: "" },
  { objectId: "9", itemId: "14", rangeEnumeration: "0..255 bytes", unit: "" },
  { objectId: "9", itemId: "15", rangeEnumeration: "0..255 bytes", unit: "" },
];
